### ISSUE TITLE
Add Event History to User Profiles

### ISSUE THREAD

**Issue by DoctorSoup143** [DoctorSoup143/KTN-Dev#10] opened 2023-08-09 23:40 UTC
Create a database and system that tracks the events a user participates in, the amount of events they have won, the number of kills acquired, and their Kick link.

---

Checklist
- [ ] Event Count
- [ ] Wins Count
- [ ] Career Kills
- [ ] Kick Link

**Comment by mphacker** [comment] 2023-09-24 15:34
This is the Result table in the database which links to an account and an event.  The display of this information will be on the public profile page for the player.

**Comment by mphacker** [comment] 2023-10-15 16:27
duplicate of #39

**Closed by mphacker** 2023-10-15 16:27 UTC
Labels: duplicate
